config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: "pages#home"
  post "/", to: "pages#ho", as: "first_search"
  post "/restaurants", to: "restaurants#index"

  resources :users, only: [:show]
  resources :restaurants, only: %i[index show] do
    resources :slots, only: %i[index]
    resources :favourite_restaurants, only: %i[create]
    # resources :covers, only: %i[]
  end

  resources :covers, only: [] do
    resources :slots, only: %i[create]
  end
  resources :slots, only: [] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy] do
    # confirmation doesn't need to be nested; could just call current_user.bookings.last on confirmation page
    get "confirmation", to: "bookings#confirmation", as: :confirmation
  end

  get "my_bookings", to: "bookings#my_bookings", as: :my_bookings
  resources :favourite_restaurants, only: %i[destroy]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/slot.rb
class Slot < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :cover
  has_one :restaurant, through: :cover

  validates :restaurant, presence: true
  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    date = params.dig(:query, :date)
    needed_at = params.dig(:query, :time).to_i
    @available_slots = @restaurant.slots.where("start_time = ?", needed_at).where("date = ?", date)
  end
end

app/views/slots/index.html.erb
<turbo-frame id="covers-index">
  <turbo-frame id="confirmation">
    <% if user_signed_in? %>
      <% @available_slots.each_with_index do |slot, index| %>
        <%= link_to slot_bookings_path(slot), data: {turbo_method: :post }  do %>
          <p>Table <%= index + 1 %></p>
        <% end %>
      <% end %>
    <% else %>
      <% @available_slots.each_with_index do |slot, index| %>
        <%= link_to new_user_registration_path do %>
        <p>Table <%= index + 1 %></p>
        <% end %>
      <% end %>
    <% end %>
  </turbo-frame>
</turbo-frame>