config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: "pages#home"
  post "/", to: "pages#ho", as: "first_search"
  post "/restaurants", to: "restaurants#index"

  resources :users, only: [:show]
  resources :restaurants, only: %i[index show] do
    resources :slots, only: %i[index]
    resources :favourite_restaurants, only: %i[create]
    # resources :covers, only: %i[]
  end

  resources :covers, only: [] do
    resources :slots, only: %i[create]
  end
  resources :slots, only: [] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy] do
    # confirmation doesn't need to be nested; could just call current_user.bookings.last on confirmation page
    get "confirmation", to: "bookings#confirmation", as: :confirmation
  end

  get "my_bookings", to: "bookings#my_bookings", as: :my_bookings
  resources :favourite_restaurants, only: %i[destroy]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/views/shared/_footer.html.erb
<% existing_query = @params || {} %>
<div class="footer" data-controller="footer" data-action="click->footer#active">
  <div class="footer-icon">
  <% if @params.present?%>
    <%= link_to restaurants_path(restaurant: @params) do %>
      <i class="<%= "btn-active" if params[:controller] == 'restaurants' %> fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% else %>
    <%= link_to restaurants_path do %>
      <i class="<%= "btn-active" if params[:controller] == 'restaurants' %> fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
  </div>

  <div class="footer-icon">
    <%= link_to root_path do %>
      <i class="<%= "btn-active" if current_page?('/') %> fa-solid fa-house"></i>
    <% end %>
  </div>

  <div class="footer-icon">
    <% if user_signed_in? %>
      <%= link_to user_path(current_user) do %>
        <i class="<%= "btn-active" if params[:controller] == 'users'  %> fa-regular fa-user"></i>
      <% end %>
      <% else %>
        <i class="fa-regular fa-user"></i>
    <% end %>
  </div>
</div>

app/views/shared/_index_card.html.erb
<div class="cards">
  <% @restaurants.each do |restaurant| %>
    <div class="card-container">
      <div class="card">
            <% if user_signed_in? && current_user.favourite_restaurants.includes(:restaurant).where('restaurant_id = ?', restaurant.id).present? %>
              <i class="fa-heart fa-solid"></i>
            <% else %>
              <i class="fa-regular fa-heart"></i>
            <% end %>

        <%= link_to restaurant_path(restaurant.id, restaurant: {
            address: @params["address"],
            date: @params["date"],
            total_seats_available: @params["total_seats_available"],
            opening_time: @params["opening_time"],
            closing_time: @params["closing_time"]
          }) do %>
          <div class="card-content">
            <div class="restaurant-img">
              <%= cl_image_tag restaurant.photo.key, height: 100, width: 100, crop: :fill  %>
            </div>
            <div class="restaurant-info">
              <h3><%= restaurant.name %></h3>
              <% (restaurant.price).times do %>
                <i class="fa-solid fa-sterling-sign" id="price-dark"></i>
              <% end %>
              <% (3 - restaurant.price).times do %>
                <i class="fa-solid fa-sterling-sign" id="price-light"></i>
              <% end %>
              <div class="restaurant-cuisine-rating">
                <p><%= restaurant.cuisine %></p>
                <div class="rating-box">
                  <p><%= restaurant.rating %></p>
                  <p style="width: 20px; height: 20px"><%= image_tag("Star.png") %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_index_card_favourites.html.erb
<% if @favourites.empty? %>
  <p>Why not favourite some restaurants to be the first to hear when they have an available seat!</p>
<% end %>
<div class="slider" data-controller="swipe">
  <% @favourites.each do |favourite| %>
    <%= link_to restaurant_path(favourite.restaurant.id) do %>
      <div class="slide">
        <div class="favourite_card d-flex">
          <%= cl_image_tag favourite.restaurant.photo.key, height: 100, width: 100, crop: :fill %>
          <div class="d-flex align-items-start flex-column" style="height: 20px; padding-top: 10px; padding-left: 18px">
            <div class="d-flex justify-content-between align-items-center favourite_name" style="width: 8em;">
              <h4><strong><%= favourite.restaurant.name %></strong></h4>
              <%= link_to favourite_restaurant_path(favourite), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-regular fa-trash-can"></i>
            <% end %>
            </div>
            <div>
              <% (favourite.restaurant.price).times do %>
                <i class="fa-solid fa-sterling-sign" id="price-dark"></i>
              <% end %>
              <% (3 - favourite.restaurant.price).times do %>
                <i class="fa-solid fa-sterling-sign" id="price-light"></i>
              <% end %>
            </div>
            <div class="d-flex justify-content-between rating">
              <div>
                <%= favourite.restaurant.cuisine %>
              </div>
              <div class="yes-you-can">
                <%= favourite.restaurant.rating %>
                <%= image_tag("Star.png") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_index_card_show_page.html.erb
<div class="cards">
    <div class="card-container">
      <div class="card">
        <i class="fa-regular fa-heart"></i>
        <%= link_to restaurant_path(@restaurant_sample.id, restaurant: {
            address: @params["address"],
            date: @params["date"],
            total_seats_available: @params["total_seats_available"],
            opening_time: @params["opening_time"],
            closing_time: @params["closing_time"]
          }) do %>

          <div class="card-content">
            <div class="restaurant-img">
              <%= cl_image_tag @restaurant_sample.photo.key, height: 100, width: 100, crop: :fill  %>
            </div>
            <div class="restaurant-info">
              <h3><%= @restaurant_sample.name %></h3>
              <% (@restaurant_sample.price).times do %>
                <i class="fa-solid fa-sterling-sign" id="price-dark"></i>
              <% end %>
              <% (3 - @restaurant_sample.price).times do %>
                <i class="fa-solid fa-sterling-sign" id="price-light"></i>
              <% end %>
              <div class="restaurant-cuisine-rating">
                <p><%= @restaurant_sample.cuisine %></p>
                <div class="rating-box">
                  <p><%= @restaurant_sample.rating %></p>
                  <p style="width: 20px; height: 20px"><%= image_tag("Star.png") %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/shared/_map.html.erb
<div id="map" style="width: 100%; height: 70vh; border-radius: 30px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
  class: "dropdown-item" %>

app/views/shared/_popup.html.erb
<h2><%= restaurant.name %></h2>

app/views/shared/_tablemodal.html.erb
<div class="modal fade" id="tableSelectModal" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="modal-title" id="exampleModalToggleLabel">Choose a table</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="tables-display">
                <% @restaurant.covers.each_with_index do |cover, index| %>
                  <div class="table-display">
                    <%= index + 1 %>
                  </div>
                <% end %>
              </div>
          </div>
          <div class="modal-footer">
            <button class="button purple medium" data-bs-target="#bookingConfirmModal" data-bs-toggle="modal">Continue</button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="bookingConfirmModal" aria-hidden="true" aria-labelledby="exampleModalToggleLabel3" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <i data-bs-target="#tableConfirmModal" data-bs-toggle="modal" class="fa-solid fa-arrow-left"></i>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="confirm-summary">
              <h2>Confirm booking</h2>
              <p><%= @restaurant.name %></p>
              <%# <p>at <%= @booking.start_time %></p>
              <%# <p>for <%= @booking.slot.cover.seats %></p>
            </div>
          </div>
          <div class="modal-footer">
            <button class="button light medium">Edit booking</button>
            <button class="button purple medium" data-bs-target="#bookingConfirmModal" data-bs-toggle="modal">Confirm</button>
          </div>
        </div>
      </div>
    </div>