config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: "pages#home"
  post "/", to: "pages#ho", as: "first_search"
  post "/restaurants", to: "restaurants#index"

  resources :users, only: [:show]
  resources :restaurants, only: %i[index show] do
    resources :slots, only: %i[index]
    resources :favourite_restaurants, only: %i[create]
    # resources :covers, only: %i[]
  end

  resources :covers, only: [] do
    resources :slots, only: %i[create]
  end
  resources :slots, only: [] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy] do
    # confirmation doesn't need to be nested; could just call current_user.bookings.last on confirmation page
    get "confirmation", to: "bookings#confirmation", as: :confirmation
  end

  get "my_bookings", to: "bookings#my_bookings", as: :my_bookings
  resources :favourite_restaurants, only: %i[destroy]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :covers, dependent: :destroy
  has_many :favourite_restaurants, dependent: :destroy
  has_many :slots, through: :covers
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :rating, presence: true
  validates :address, presence: true
  validates :cuisine, presence: true
  validates :price, presence: true
  validates :price, numericality: { only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 3 }
  validates :description, presence: true
  validates :date, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if all_search_params_present?
      @restaurant_address = params.dig(:restaurant, :address)
      @date = params.dig(:restaurant, :date)
      @needed_seats = params.dig(:restaurant, :total_seats_available).to_i
      @needed_after = params.dig(:restaurant, :opening_time).to_i
      @needed_before = params.dig(:restaurant, :closing_time).to_i
      restaurants_by_address = Restaurant.where("address LIKE ?", "%#{@restaurant_address.capitalize}%")
      restaurants_by_address = filter_by_cuisine_and_rating(restaurants_by_address)

      restaurant_by_address_ids = restaurants_by_address.map(&:id)

      covers = Cover.where("seats > ?", @needed_seats).where(restaurant_id: restaurant_by_address_ids)
      cover_ids = covers.map(&:id)
      slots = Slot.where("start_time >= ?", @needed_after)
        .where("start_time <= ?", @needed_before)
        .where(cover_id: cover_ids)
        .where("date = ?", @date).uniq

      restaurant_ids = slots.map { |slot| slot.restaurant.id }.uniq
      @restaurants = Restaurant.where(id: restaurant_ids)
      @params = request.query_parameters["restaurant"]

      @markers = @restaurants.geocoded.map do |restaurant|
        if restaurant.id == 1
          {
            lat: 51.549723,
            lng: -0.057367,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 4
          {
            lat: 51.5205,
            lng: 0.1014,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 5
          {
            lat: 51.5384,
            lng: -0.07592,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 7
          {
            lat: 51.5499,
            lng: 0.1090,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 8
          {
            lat: 51.5226,
            lng: 0.1060,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 12
          {
            lat: 51.52435,
            lng: 0.02942,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 14
          {
            lat: 51.52447,
            lng: -0.07438,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        else
          {
            lat: restaurant.latitude,
            lng: restaurant.longitude,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        end
      end
    else
      @params = {
        address: "London",
        date: Date.new(2022,12,9),
        total_seats_available: 2,
        opening_time: 9,
        closing_time: 23
      }
      @restaurants = Restaurant.all
      @restaurant_address = "London"
      @date = Date.new(2022,12,9)
      @needed_seats = 2
      @needed_after = 9
      @needed_before = 23

      @restaurants = filter_by_cuisine_and_rating(@restaurants)

      @markers = @restaurants.geocoded.map do |restaurant|
        if restaurant.id == 1
          {
            lat: 51.549723,
            lng: -0.057367,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 4
          {
            lat: 51.5205,
            lng: 0.1014,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 5
          {
            lat: 51.5384,
            lng: -0.07592,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 7
          {
            lat: 51.5499,
            lng: 0.1090,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 8
          {
            lat: 51.5226,
            lng: 0.1060,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 12
          {
            lat: 51.52435,
            lng: 0.02942,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        elsif restaurant.id == 14
          {
            lat: 51.52447,
            lng: -0.07438,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        else
          {
            lat: restaurant.latitude,
            lng: restaurant.longitude,
            info_window: render_to_string(partial: "shared/popup", locals: { restaurant: restaurant })
          }
        end
      end
    end
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    needed_seats = params.dig(:restaurant, :total_seats_available).to_i
    available_covers = @restaurant.covers.where("seats >= ?", needed_seats)
    available_covers_ids = available_covers.map(&:id)

    date = params.dig(:restaurant, :date).present? ? params.dig(:restaurant, :date) : Date.new(2022,12,9)
    needed_after = params.dig(:restaurant, :opening_time).present? ? params.dig(:restaurant, :opening_time).to_i : 9
    needed_before = params.dig(:restaurant, :closing_time).present? ? params.dig(:restaurant, :closing_time).to_i : 21
    @available_slots = @restaurant.slots.where(available?: true)
          .where("start_time >= ?", needed_after)
          .where("start_time <= ?", needed_before)
          .where("date = ?", date)
          .where(cover_id: available_covers_ids).select(:start_time).distinct

    @markers = [{ lat: @restaurant.latitude, lng: @restaurant.longitude }]
    if all_search_params_present?
      @params = request.query_parameters["restaurant"]
    else
      @params = {
        address: "London",
        date: Date.new(2022,12,9),
        total_seats_available: 2,
        opening_time: 9,
        closing_time: 23
      }
    end
    # @params = request.query_parameters["restaurant"]
    @restaurant_sample = Restaurant.where("rating > 4").sample
  end

  private

  def filter_by_cuisine_and_rating(restaurants)
    return restaurants if !params[:restaurant]

    if params[:restaurant].has_key?(:cuisine) || params[:restaurant].has_key?(:price)
      cuisine = params[:restaurant][:cuisine][1] if params[:restaurant][:cuisine][1].present?
      price = params[:restaurant][:price][1] if params[:restaurant][:price][1].present?
      if params[:restaurant][:cuisine][1].present?
        restaurants = restaurants.where("cuisine LIKE ?", cuisine)
      end

      if params[:restaurant][:price][1].present?

        restaurants = restaurants.where("price = ?", price)
      end
    end

    restaurants
  end

  def all_search_params_present?
    params[:restaurant].present? &&
    params.dig(:restaurant, :address).present? &&
    params.dig(:restaurant, :date).present? &&
    params.dig(:restaurant, :total_seats_available).present? &&
    params.dig(:restaurant, :opening_time).present? &&
    params.dig(:restaurant, :closing_time).present?
  end
end

app/views/restaurants/index.html.erb
<div class="container">
  <div class="index-header">
    <h2>Your search</h2>
    <button type="button"
      class="search-select" data-bs-toggle="modal"
      data-bs-target="#filterModal">
      Filter  <%= image_tag("filter.png") %>
    </button>
    <div class="modal fade" id="filterModal" aria-hidden="true"
      aria-labelledby="exampleModalToggleLabel" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h2>Filters</h2>
            <button type="button" data-bs-dismiss="modal" aria-label="Close">X</button>
          </div>
          <div class="modal-body">
            <%= simple_form_for(@restaurant, method: :get) do |f| %>
              <div class="filter-section">
                <h3>Cuisine</h3>
                <div class="form">
                  <%= f.input :cuisine,
                    as: :check_boxes,
                    collection_wrapper_tag: 'div',
                    collection_wrapper_class: 'filter-list',
                    item_wrapper_class: 'filter',
                    input_html: {class: 'filter-check'},
                    collection: ["Italian", "Japanese", "Indian", "Chinese", "Thai", "Spanish", "Middle Eastern", "Turkish", "Mexican", "British", "French", "Malaysian", "Taiwanese",
                    "Seafood", "North African", "West African", "Gastropubs", "Contemporary European", "Fusion", "Vegetarian"] %>
                </div>
              </div>
              <div class="filter-section">
                <h3>Price</h3>
                  <%= f.input :price,
                    as: :check_boxes,
                    collection_wrapper_tag: 'div',
                    collection_wrapper_class: 'filter-list',
                    item_wrapper_class: 'filter',
                    input_html: {class: 'filter-check'},
                    collection:  {"£" => 1, "££" => 2, "£££" => 3}
                     %>
              </div>
              <%= f.hidden_field :address, value: @params[:address] %>
              <%= f.hidden_field :date, value: @params[:date] %>
              <%= f.hidden_field :opening_time, value: @params[:opening_time] %>
              <%= f.hidden_field :closing_time, value: @params[:closing_time] %>
              <%= f.hidden_field :total_seats_available, value: @params[:total_seats_available] %>
              <div class="modal-footer"></div>
              <%= f.submit "Apply", class: "button purple" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to root_path(anchor: 'home-form'), style: "text-decoration: none" do %>
  <div class="form-input results">
    <span><%= @restaurant_address %>, <%= @date %>, <%= @needed_after %> - <%= @needed_before %>, <%= @needed_seats %> guests </span>
  </div>
  <% end %>
  <div class="index-items">
    <div class="menu nav-btns">
      <ul class="nav nav-pills" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <input class="menu_input nav-link active" id="btn2 pills-home-tab" name="menu" type="radio" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true" />
            <label class="menu_label" for="btn2 pills-home-tab">
              <div class="fa fa-bars"></div>
              <div class="menu_text">
              List
              </div>
            </label>
        </li>

        <li class="nav-item" role="presentation">
          <input class="menu_input nav-link" id="btn3 pills-profile-tab" name="menu" type="radio" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="true" />
            <label class="menu_label" for="btn3 pills-profile-tab">
              <div class="fa fa-map-pin"></div>
              <div class="menu_text">
                Map
              </div>
            </label>
        </li>
      </ul>
    </div>

    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0"><%= render "shared/index_card" %></div>
      <div class="map tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0"><%= render "shared/map" %></div>
    </div>
  </div>

</div>

app/views/restaurants/show.html.erb
<div class="restaurant-images">
  <%= cl_image_tag @restaurant.photo.key %>
</div>
<div class= container>
  <div class="show-section">
    <div class="restaurant-heading">
      <h2><%= @restaurant.name %></h2>
      <div class="rating-box">
        <p><%= @restaurant.rating %></p>
        <p style="width: 20px; height: ;eight: 20px"><%= image_tag("Star.png") %></p>
      </div>
    </div>
    <div class="restaurant-cuisine-show">
      <p><%= @restaurant.cuisine %></p>
    </div>
    <div class="restaurant-buttons">
      <div class="maps-button"  data-bs-toggle="modal" data-bs-target="#restaurantFilterModal">
        <p>See on maps</p>
      </div>
      <div class="reviews-button">
        <a href="#reviews-container" class="review-button" data-controller="scroll-to">Read reviews</a>
      </div>
    </div>
  </div>
  <div class="favourite-heart heart-background">
      <%= link_to restaurant_favourite_restaurants_path(@restaurant), data: {turbo_method: :post} do %>
        <% if user_signed_in? && current_user.favourite_restaurants.includes(:restaurant).where('restaurant_id = ?', @restaurant.id).present? %>
          <i class="fa-heart fa-solid" data-controller="fill-heart" data-action="click->fill-heart#animation"></i>
        <% else %>
          <i class="fa-regular fa-heart" data-controller="fill-heart" data-action="click->fill-heart#animation"></i>
        <% end %>
      <% end %>
  </div>


  <div class="modal fade" id="restaurantFilterModal" aria-hidden="true" aria-labelledby="restaurantFilterModalLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalToggleLabel2">Location</h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "shared/map" %>
        </div>
      </div>
    </div>
  </div>

  <button type="button" class="button purple time-select" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Select a time
  </button>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">New booking</h1>
          <button type="button" data-bs-dismiss="modal" aria-label="Close">X</button>
        </div>
        <div class="modal-body" style="overflow-y: scroll">
          <div class="restaurant-times">
            <div class="restaurant-times-grid">
              <turbo-frame id="covers-index" class="tables-display">
                <div class="tables-display">
                  <% @available_slots.each do |slot| %>
                      <%= link_to restaurant_slots_path(@restaurant, query: {date: @params[:date], time: slot.start_time}) do %>
                      <div class="time-slot">
                        <p><%= slot.start_time %> : 00</p>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </turbo-frame>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="show-section">
    <div class="restaurant-description">
      <p><%= @restaurant.description %></p>
    </div>
  </div>
  <div class="show-section">
    <div class="reviews" id="reviews-container">
      <div class="reviews-header"><h2>See what people are saying:</h2></div>
      <p><%= @restaurant.reviews.count %> reviews</p>
      <p><% @restaurant.reviews.each do |review| %></p>
        <div class="reviews-details">
          <div class="review-name-rating">
            <div>
              <p><strong><%= review.user.name %></strong></p>
            </div>
            <div class="review-stars">
              <% rand(3..4).times do %>
              <%= image_tag("Star.png") %>
              <% end %>
            </div>
          </div>

          <div class="review-content"><p><%= review.content %></p></div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="show-section">
    <div class="more-restaurants">
      <div class="more-restaurants-header"><h2>More tables at</h2></div>
      <div class="restaurant-cards-small row">
        <%= render "shared/index_card_show_page" %>
      </div>
    </div>
  </div>
</div>